Add __getattr__ to LazyDataFrame
scikit-hep/coffea pull request #176
Opened 2019-10-11 07:28 UTC by paulgessinger

Using `__getattr__`, one can access columns from lazy dataframe like `df.electron_pt` in addition to `df["electron_pt"]`. This just forwards to `__getitem__` which is obviously already implemented.

Pandas something like this, so I thought it makes sense to have it here as well. (Also I prefer it 😄 )

2019-10-11 12:44 UTC, lgray commented
Have you checked that this does not interfere with access to class member functions in the base class or derived classes?

2019-10-11 13:28 UTC, paulgessinger commented
As per https://docs.python.org/3/reference/datamodel.html#object.__getattr__, the interpreter tries to look up the given key in the class itself as well as the class tree, before invoking `__getattr__`, so I think it should be safe.

2019-10-11 14:17 UTC, lgray commented
Seems to be the same for python2.

Can you add tests of the new functionality to:
https://github.com/CoffeaTeam/coffea/blob/master/tests/test_processor.py
(data frame tests at the bottom)

Thanks!

2019-10-11 15:36 UTC, nsmith- commented
Yeah there was a lot of FUD about `__getattr__` that turns out to be mostly related to the much more dangerous `__getattribute__`.  But nevertheless, a google search shows that it can be implemented safely.

2019-10-11 15:40 UTC, nsmith- requested changes
While you're there, can you add also the same to PreloadedDataFrame?

2019-10-11 15:40 UTC, nsmith- commented on coffea/processor/dataframe.py
> +        return self.__getitem__(key)
So one issue here is that when an item isn't  there, a `KeyError` is raised which leads to a misleading error message and less useful stack trace.  To avoid, maybe better to format as:
```python
        try:
            return self[key]
        except KeyError:
            raise AttributeError
```

2019-10-14 11:02 UTC, paulgessinger commented on coffea/processor/dataframe.py
> +        return self.__getitem__(key)
Should be this way now.

2019-10-14 11:03 UTC, paulgessinger commented
I added tests, basically copied from the ones for `__getitem__` with minor changes. I didn't implement `__setattr__` (this is a bit difficult), so I dropped one assertion in the copied test.

2019-10-14 22:02 UTC, lgray commented on coffea/processor/dataframe.py
> +        return self.__getitem__(key)
Looks like it's all there now.

2019-10-14 22:03 UTC, lgray approved these changes

2019-10-14 22:04 UTC, lgray commented
Looks all good to me. Thanks for adding the tests and improve the error reporting!

2019-10-14 22:04 UTC, merged