Ressurect systematics handling (first eager then delayed)
scikit-hep/coffea pull request #786
Opened 2023-04-10 20:36 UTC by lgray

Getting the systematics book-keeping back into working order.

@alexander-held 

The awkward / dask-awkward / dask-histogram pins + this will make the next rc.

2025-07-07 20:48 UTC, lgray commented
ok, was able to save that recent patch.

2025-07-11 21:16 UTC, lgray commented
@ikrommyd aside from a little bit of comment/dead code clean up this is ready for review.

2025-07-12 00:06 UTC, ikrommyd requested changes
Hi @lgray, I tested the `add_systematic` locally and it seems to work and gives me the same result of dask and virtual modes. Could we have a unit test please (`test_nanoevents_systematics.py` or something)? You could just steal the `muon_pt_scale` example from the notebook and just assert that virtual and dask results are equal to the eager one :)

2025-07-12 12:49 UTC, lgray commented
Thanks, will attend to this momentarily!

2025-07-12 14:23 UTC, lgray commented
@ikrommyd Should be what you were looking for now, please have a look.

2025-07-12 15:13 UTC, ikrommyd approved these changes

2025-07-12 15:14 UTC, ikrommyd commented
Perfect! Thanks :)

2025-07-12 15:14 UTC, merged

2025-07-12 15:25 UTC, lgray commented
oops - there's a small confusing typo... I'll submit a quick PR